### ISSUE TITLE
Task browsersync is not configured as a task on gulp

### ISSUE THREAD

**Issue by eugeneross** [switchbitio/ghost-theme-with-gulp#3]
If anyone is receiving the issue 'Task browsersync is not configured as a task on gulp' you need to go into your `ghost.js` file and change this:

```
g.then(function (ghostServer) {
        ghostServer.start().then(function () {
          runSequence('browsersync');
        });
  });
```

to this:

```
g.then(function (ghostServer) {
        ghostServer.start().then(function () {
          runSequence('browser-sync');
        });
  });
```

adding the dash solved the issue, not sure if it was an initial typo or something changed within dependencies. 

You will also have to check other files that have `browsersync` and change them to `browser-sync`.

**Comment by donovanmuller** [comment]
Which branch was this on? I'm assuming [part3](https://github.com/switchbitio/ghost-theme-with-gulp/tree/part3)...

The [`browsersync`](https://github.com/switchbitio/ghost-theme-with-gulp/blob/part3/gulp/tasks/browsersync.js#L4) task resides in [`browsersync.js`](https://github.com/switchbitio/ghost-theme-with-gulp/blob/part3/gulp/tasks/browsersync.js).
I.e. `browsersync` in [`ghost.js`](https://github.com/switchbitio/ghost-theme-with-gulp/blob/part3/gulp/tasks/ghost.js#L22) is a valid reference to the `browsersync` task in [`browsersync.js`](https://github.com/switchbitio/ghost-theme-with-gulp/blob/part3/gulp/tasks/browsersync.js).

I've tried to reproduce this but all good on my side (always is though 😄).

Would you mind describing the steps you follow when you get this?
Node and NPM versions would also be helpful.

**Comment by eugeneross** [comment]
I followed your Part 2 post line by line and received that error, but the dashes fixed it. The code on Part 2 and Part 3 branches show the non dashed `browsersync`. I understand it was a reference, so I'm thinking later on the change will mess something up down the line...

Node version: 4.4.5
NPM version: 2.14.7

**Comment by donovanmuller** [comment]
Ah ok, the code snippet in the post was incorrect:

<img width="1030" alt="screen shot 2016-06-15 at 9 48 02 pm" src="https://cloud.githubusercontent.com/assets/1175891/16095075/554545d0-3343-11e6-85f5-b92a7b2e490b.png">

I have updated the post to reference the `browsersync` task now.

Thanks for creating the issue and highlighting the error 👍
