### ISSUE TITLE
Wiredep not injecting dependencies

### ISSUE THREAD

**Issue by eugeneross** [switchbitio/ghost-theme-with-gulp#4]
I followed your Part 3 tutorial up until the part where you run:

```
$ gulp install
$ gulp wiredep
```

So without running `npm install` the `gulp install` command complains it can't find `wiredep`. After running a `npm install` then running `gulp install` it says there is no task named "install." I then run `gulp wiredep` and receive no changes in my `default.hbs` file. 

I'm curious to why you're running `gulp install`.

**Comment by donovanmuller** [comment]
Arg, typo. Should read:

<img width="1026" alt="screen shot 2016-06-15 at 10 55 36 pm" src="https://cloud.githubusercontent.com/assets/1175891/16097120/5d97ba48-334c-11e6-8263-cd2f9793fb03.png">

```
$ npm install
$ gulp wiredep
```

have updated post. Thanks again.

**Comment by eugeneross** [comment]
Awesome! Although, `wiredep` doesn't seem to be injecting the dependencies. I have my normalize component within my `bower_components`  as it should be.

**Comment by donovanmuller** [comment]
Are you referring to this section?

<img width="1050" alt="screen shot 2016-06-15 at 11 01 42 pm" src="https://cloud.githubusercontent.com/assets/1175891/16097248/2dd62db6-334d-11e6-84f3-b1fbdde46097.png">

**Comment by eugeneross** [comment]
That one and the one before that uses just `gulp wired`.
<img width="1004" alt="screen shot 2016-06-15 at 2 13 00 pm" src="https://cloud.githubusercontent.com/assets/174520/16097588/6673db5e-3303-11e6-8fce-354b4b160b06.png">

**Comment by donovanmuller** [comment]
You definitely added the `wiredep` tasks in `/gulp/tasks/wiredep.js` and `wiredep-scss` in `/gulp/tasks/wiredep-scss.js` right?

If you're still stuck, you can put your code up somewhere (Github etc.) and I can take a look...

**Comment by eugeneross** [comment]
Yes, anything I did differently was just using `.sass` instead of `.scss` as a personal preference for syntax, also changed the file name.

[`wiredep.js`](http://pastebin.com/7ux8NLeV)
[`wiredep-sass.js`](http://pastebin.com/P7ihNAEK)

**Comment by donovanmuller** [comment]
Your `wiredep-sass` task is injecting the `normalize.scss` into `app/assets/css`.
This should be injecting into the same source file. I.e. your [`wiredep-sass.js`](http://pastebin.com/P7ihNAEK) should look like:

```
var gulp = require('gulp');
var wiredep = require('wiredep').stream;

gulp.task('wiredep:sass', function () {
  return gulp
    .src('./src/sass/**/*.sass')
    .pipe(wiredep({
      ignorePath: /^(\/|\.+(?!\/[^\.]))+\.+/,
      fileTypes: {
        sass: {
          replace: {
            sass: '@import "app{{filePath}}";'
          }
        }
      }
    }))
    .pipe(gulp.dest('src/assets/sass'));
});
```

I assume you've catered the folder structure to your needs and that's why you're using `src` instead of `app`? Given the above I was able to inject into my `app/assets/sass/screen.sass` (in my structure)

**Comment by eugeneross** [comment]
@donovanmuller Yes, you are correct, and thanks for correcting my mistake!
